version: 2

registries:
  github-maven:
    type: maven-repository
    url: https://maven.pkg.github.com/equinor/
    username: x-access-token # username doesn't matter
    password: ${{ secrets.PACKAGES_USER_TOKEN }} # dependabot secret

updates:
  - package-ecosystem: github-actions
    open-pull-requests-limit: 10
    directories:
      - '/'
      # all composite actions must be individually listed here
      # https://github.com/dependabot/dependabot-core/issues/6704
      - '/.github/actions/azure-firewall'
      - '/.github/actions/build-and-push'
      - '/.github/actions/deploy'
      - '/.github/actions/release-find-version'
      - '/.github/actions/run-checkstyle'
    ignore:
      # ignore private GitHub Action that Dependabot doesn't have access to
      - dependency-name: 'equinor/oilmod1-release-actions'
    schedule:
      interval: weekly
      day: sunday
    commit-message:
      prefix: chore
      include: scope
    labels:
      - github-actions
      - dependencies
    groups:
      github-actions:
        patterns:
          # use wildcard to bundle plugins and libs into one PR
          - "*"

  - package-ecosystem: maven
    directory: '/'
    schedule:
      interval: weekly
      day: sunday
    commit-message:
      prefix: chore
      include: scope
    labels:
      - java
      - maven
      - dependencies
      - parent-pom
    registries:
      - github-maven
    groups:
      parent-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          # Exclude any module-specific dependencies that might be declared in parent
          - "com.example.module*"

  - package-ecosystem: maven
    directory: '/module1'
    schedule:
      interval: weekly
      day: sunday
    commit-message:
      prefix: chore
      include: scope
    labels:
      - java
      - maven
      - dependencies
      - module1
    registries:
      - github-maven

  - package-ecosystem: maven
    directory: '/module2'
    schedule:
      interval: weekly
      day: sunday
    commit-message:
      prefix: chore
      include: scope
    labels:
      - java
      - maven
      - dependencies
      - module2
    registries:
      - github-maven

  - package-ecosystem: maven
    directory: '/module3'
    schedule:
      interval: weekly
      day: sunday
    commit-message:
      prefix: chore
      include: scope
    labels:
      - java
      - maven
      - dependencies
      - module3
    registries:
      - github-maven
