name: Dependency Submission

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches: [ main, develop ]
    paths:
      - 'pom.xml'
      - '**/pom.xml'
      - 'settings.xml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'pom.xml'
      - '**/pom.xml'
      - 'settings.xml'
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sundays at midnight

# only allow minimum required permissions at top-level
permissions: {}

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for dependency submission

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      
      - name: Setup Java
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          java-version: 21
          distribution: temurin
          cache: maven
      
      # Make Maven wrapper executable
      - name: Make Maven wrapper executable
        run: chmod +x ./mvnw
      
      # Submit dependencies to the GitHub dependency graph
      - name: Submit Dependency Snapshot
        uses: advanced-security/maven-dependency-submission-action@b275d12641ac2d2108b2cbb7598b154ad2f2cee8 # v5.0.0
        env:
          PACKAGES_USER_NAME: ${{ vars.PACKAGES_USER_NAME }}
          PACKAGES_USER_TOKEN: ${{ secrets.PACKAGES_USER_TOKEN }}
        with:
          settings-file: settings.xml
