# Dependency Review Action
#
# This workflow scans pull requests for dependency changes
# and raises security alerts for vulnerable dependencies
name: 'Dependency Review'

on:
  pull_request:
    branches: [ "main", "develop" ]

# only allow minimum required permissions at top-level
permissions: {}

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write  # Required for the dependency submission action

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Fetch all history to ensure proper dependency comparisons
      
      - name: Setup Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Make Maven wrapper executable
        run: chmod +x ./mvnw

      - name: Submit Dependency Snapshot
        uses: advanced-security/maven-dependency-submission-action@v3
        with:
          maven-args: "-f pom.xml"
      
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          # Possible values: critical, high, moderate, low
          fail-on-severity: critical
          
          # Comment on PRs with security failures
          comment-summary-in-pr: true
