# Dependency Review Action
#
# This workflow scans pull requests for dependency changes
# and raises security alerts for vulnerable dependencies
#
# When started in manual mode it will check the entire history

name: 'Dependency Review'
on: [ pull_request, workflow_dispatch ]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: "Get the first commit SHA"
        if: github.event_name == 'workflow_dispatch'
        id: first-commit
        run: echo "first_commit_sha=$(git rev-list --max-parents=0 HEAD)" >> $GITHUB_ENV
      - name: 'Dependency Review (manual)'
        if: github.event_name == 'workflow_dispatch'
        uses: actions/dependency-review-action@v4
        with:
          base-ref: ${{ env.first_commit_sha }}
          head-ref: ${{ github.ref }}
          show-openssf-scorecard: true
          vulnerability-check: true
          license-check: true
          warn-only: true
      - name: 'Dependency Review (pull_request)'
        if: github.event_name == 'pull_request'
        uses: actions/dependency-review-action@v4
        with:
          show-openssf-scorecard: true
          vulnerability-check: true
          license-check: true
